### ISSUE TITLE
Does this support .sql file as changeset?

### ISSUE THREAD

**Issue by gauagarw0** [cloudspannerecosystem/liquibase-spanner#105]
Hi am trying to upgrade my existing system and have already setup process accorss multiple work streams to produce .sql files and then we merge all .sql files to a chanesetfile.sql.
But now I see this processes yaml. On providing .sql file, liquibase failed to parse it.

Can you please confirm if there is away to make it support sql file?

**Comment by mescanne** [comment]
Gaurav -- this should work equally well with SQL formatted Liquibase changesets. In fact, it is simpler as you're responsible for writing Spanner SQL while the other changeset formats uses Liquibase SQL generation.

If you can provide a specific simple example of where it is failing, that would be helpful.

**Comment by mescanne** [comment]
Closing. Please re-open/raise another issue if there's still an issue.
