### ISSUE TITLE
Spanner / GCP library dependency management

### ISSUE THREAD

**Issue by husseyd** [cloudspannerecosystem/liquibase-spanner#118]
The current pom.xml version manages GCP libraries to those under `libraries-bom` 23.1.0 which is from Sept '21 - see below.
The latest right now is 25.3.0 from May '22. There's no specific feature or bug arising from this, only that it locks us to use older version of Spanner libraries which may be missing improvements.

Eg currently locked to ~ spanner libs 6.12.5, latest being 6.25.4.

Flagging for visibility only - this isn't causing a problem at this point in time (for me).

``` 
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>libraries-bom</artifactId>
        <version>23.1.0</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
...
```

**Comment by olavloite** [comment]
Closing this, as the newest releases uses up to date GCP library versions.
