### ISSUE TITLE
Support customized changelog and lock tables

### ISSUE THREAD

**Issue by cbuschka** [cloudspannerecosystem/liquibase-spanner#121]
Dear Liquibase-Spanner devs,

thanks for providing the liquibase extension for spanner.

In our project we would like to use a custom databasechangelog and lock table name. A brief look into the code showed that the table names currently are hard coded. As liquibase already provides support for customized table names, it looked easy to replace the names in the sql templates to enable table name configuration.

Please review and merge the change.

In case s.th. is missing, I would be happy to add it.

Best
Conni (he/him)

**Comment by olavloite** [comment]
Fixed in #122
