### ISSUE TITLE
May I know the reason for jar files not being uploaded as part of the release

### ISSUE THREAD

**Issue by dileepkumar457** [cloudspannerecosystem/liquibase-spanner#192]
I was looking for the liquibase-spanner{version}-all.jar in the latest versions. It is not being released after version 4.17.1
I am facing compatibility issues when I try to use the jar which I created including dependencies.
Request to update the documentation with steps to generate liquibase-spanner{version}-all.jar file.

**Comment by dmanci** [comment]
@olavloite Was this a change in the release process or a mistake?

**Comment by olavloite** [comment]
Hmm.... Thanks for flagging this. It was not a deliberate change, and I also don't know of any specific changes to the release process that might have caused this. I'll take a look.

**Comment by olavloite** [comment]
@dileepkumar457 I've added the .jar files to the newest releases. Would you mind trying those?

The tests ran successfully for those .jars for me, but you mentioned that you had some compatibility issues when you tried to create one manually. Please let me know if that is also the case with the .jars that have been added to the newest releases, and what the error is that you are seeing.
