### ISSUE TITLE
Does it support DDL - GRANT?

### ISSUE THREAD

**Issue by gauagarw0** [cloudspannerecosystem/liquibase-spanner#193]

**Comment by olavloite** [comment]
Yes. The extension supports Liquibase's sql change set type: https://docs.liquibase.com/change-types/sql.html

You can use that to execute any type of DDL statement that Cloud Spanner supports, including [`GRANT`](https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#grant_statement) statements.
