### ISSUE TITLE
Specify spanner query priority?

### ISSUE THREAD

**Issue by jduan-highnote** [cloudspannerecosystem/liquibase-spanner#226]
Hi,

When use `liquibase execute-sql` to run queries against spanner, is there a way to specify the query priority? https://cloud.google.com/spanner/docs/reference/rest/v1/RequestOptions#Priority

**Comment by olavloite** [comment]
Yes, there are two ways to do that:

1. Use `SET RPC_PRIORITY = {'HIGH'|'MEDIUM'|'LOW'|'NULL'}`
2. Use a hint (only supported using the [Spanner JDBC driver 2.17.0](https://github.com/googleapis/java-spanner-jdbc/releases/tag/v2.17.0) and higher)

### SET RPC_PRIORITY
You can use the `SET RPC_PRIORITY = {'HIGH'|'MEDIUM'|'LOW'|'NULL'}` in a SQL script to set the priority that should be used by the JDBC connection from that point on. See https://cloud.google.com/spanner/docs/jdbc-session-mgmt-commands#rpc_priority

In combination with Liquibase `execute-sql`, this means that it only works with a SQL script file, as you need to execute multiple statements.

Example:

```sql
SET RPC_PRIORITY = 'LOW';
UPDATE my_table SET active=false WHERE last_used<TIMESTAMP '2024-01-01T00:00:00Z';
```

### Use a hint

This feature was added in the [Spanner JDBC driver version 2.17.0](https://github.com/googleapis/java-spanner-jdbc/releases/tag/v2.17.0). So you need to make sure your application uses at least that version for this to work.

The hint is only applied to the specific statement, so you can also use it with single statements.

Example:

```
liquibase execute-sql --sql="@{RPC_PRIORITY=PRIORITY_LOW} UPDATE my_table SET active=false WHERE last_used<TIMESTAMP '2024-01-01T00:00:00Z'"
```
