### ISSUE TITLE
feat: Add support for INTERLEAVED table

### ISSUE THREAD

**Issue by olavloite** [cloudspannerecosystem/liquibase-spanner#27]
Cloud Spanner supports `INTERLEAVED` tables, but it is not something that is supported by other DBMS's. It is an important feature of Spanner, and it would be good to investigate whether we could add native support for it in the extension.

**Comment by mescanne** [comment]
The approach of INTERLEAVE'd tables is demonstrated here:
https://github.com/cloudspannerecosystem/liquibase-spanner/blob/master/example/create-schema.yaml#L115

I believe this is sufficient for most use cases for customers.

**Comment by olavloite** [comment]
Agree, closing this based on the samples that have been added.
