### ISSUE TITLE
loadUpdateData - is failing 

### ISSUE THREAD

**Issue by rahuldyadav** [cloudspannerecosystem/liquibase-spanner#69]
Hi 

i have update to liquibaseVersion=4.2.0 and trying to use loadUpdateData for spanner.

i am loading the csv file into spanner where i am getting below error.

Could you please ot

1) Error getting default schema
liquibase.exception.DatabaseException: Error executing SQL call current_schema: Callable statements are not supported
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)

2) Caused by: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlFeatureNotSupportedException: Callable statements are not supported
	at com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory.unsupported(JdbcSqlExceptionFactory.java:301)
3) cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Unsupported concurrency mode in query using INFORMATION_SCHEMA.

**Comment by mescanne** [comment]
Rahul -

Could you share a version of the changeset that caused this error?

We have an example [here](https://github.com/cloudspannerecosystem/liquibase-spanner/blob/master/example/load-data-singers.yaml), and the unit test is [here](https://github.com/cloudspannerecosystem/liquibase-spanner/blob/master/src/test/java/liquibase/ext/spanner/LoadUpdateDataTest.java) with the [YAML changeset](https://github.com/cloudspannerecosystem/liquibase-spanner/blob/master/src/test/resources/load-update-data-singers.spanner.yaml). If we can reproduce the issue that would help tremendously.

Thanks,
Mark

**Comment by rahuldyadav** [comment]
Hi Mark

Thank you for sharing details, yes i referred all links from documentation. still facing same issue
The feature you introduced is very important and most needed for spanner.
Thank you for sharing it.

my use case is to upgrade the liquibaseVersion from 3.8.9 to 4.2.0 to use loadupdate date for upsert implementation based on primary key.

liquibaseVersion=4.2.0
liquibaseSpannerVersion=1.0.32

<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.2.xsd"
        logicalFilePath="R13">

    <changeSet author="author" context="refdata" id="ref_code" runInTransaction="false" >
        <loadUpdateData primaryKey="CODE_ID" file="ref_file.csv"
                        tableName="REF_TABLE" schemaName="" >
            <column header="CODE_ID"   name="MEDICATION_CODE_ID" type="STRING"></column>
            <column header="DISPLAY_NAME" name="DISPLAY_NAME" type="STRING"></column>
        </loadUpdateData>
    </changeSet>

</databaseChangeLog>


Please review it.

**Comment by mescanne** [comment]
Just to check -- does anything work with Liquibase and Spanner? If the extension wasn't properly loaded this could happen. But normally it should never "call current_schema".

**Comment by rahuldyadav** [comment]
Hi
Liquibase is loading and then trying to get default schema and throwing exception  
Error getting default schema

liquibase-plugin: Running the 'main' activity...
[2021-02-25 16:55:43] INFO [liquibase.integration] No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro features.
Liquibase Community 4.2.0 by Datical
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##  Get advanced features and support at          ##
##      liquibase.com/support                     ##
##                                                ##
####################################################
Starting Liquibase at 16:55:43 (version 4.2.0 #18 built at 2020-11-13 16:49+0000)
[2021-02-25 16:55:43] WARNING [com.google.auth.oauth2.DefaultCredentialsProvider warnAboutProblematicCredentials] Your application has authenticated using end user credentials from Google Cloud SDK. We recommend that most server applications use service accounts instead. If your application continues to use end user credentials from Cloud SDK, you might receive a "quota exceeded" or "API not enabled" error. For more information about service accounts, see https://cloud.google.com/docs/authentication/.
[2021-02-25 16:56:16] WARNING [liquibase.database] Unknown database: Google Cloud Spanner
[2021-02-25 16:56:16] INFO [liquibase.database] Error getting default schema
liquibase.exception.DatabaseException: Error executing SQL call current_schema: Callable statements are not supported

**Comment by mescanne** [comment]
The "Unknown database: Google Cloud Spanner" means the extension isn't loading. It's using the default Liquibase behaviour for any old database which is why it's not working.

See the [deploying](https://github.com/cloudspannerecosystem/liquibase-spanner/blob/master/README.md#deploying) section. Once you build the extension (or download it from [here](https://github.com/cloudspannerecosystem/liquibase-spanner/releases/download/1.0.2/liquibase-spanner-1.0.2-all.jar)), you need to copy it into the Liquibase libs directory.

**Comment by mescanne** [comment]
I'm closing this. Please open a new issue if you have trouble getting it deployed and running.
