### ISSUE TITLE
liquidate-spanner and spring boot

### ISSUE THREAD

**Issue by laurentiu-miu** [cloudspannerecosystem/liquibase-spanner#74]
can this lib be integrated with spring boot without maven? 
like this https://www.baeldung.com/liquibase-refactor-schema-of-java-app

**Comment by olavloite** [comment]
@laurentiu-miu 

> can this lib be integrated with spring boot without maven?
> like this https://www.baeldung.com/liquibase-refactor-schema-of-java-app

Yes, that should be possible. The integration tests in this library also execute change sets without using Maven.

You would need to add both Liquibase core and this library to the dependencies of your project like this:

```xml
<dependency>
  <groupId>org.liquibase</groupId>
  <artifactId>liquibase-core</artifactId>
  <version>${liquibase.version}</version>
</dependency>
<dependency>
  <groupId>com.google.cloudspannerecosystem</groupId>
  <artifactId>liquibase-spanner</artifactId>
  <version>1.0.2</version>
</dependency>
```

Are you running into any specific problems with any of the examples in the [blog post](https://www.baeldung.com/liquibase-refactor-schema-of-java-app)?

**Comment by laurentiu-miu** [comment]
Hi @olavloite 10x for your response and sorry for my late response.

Adding 		
```
<dependency>
	<groupId>com.google.cloudspannerecosystem</groupId>
	<artifactId>liquibase-spanner</artifactId>
	<version>1.0.2</version>
</dependency>
```
To a spring boot project suppress all logs. Maybe is something related to logbook.xml

[Git demo](https://github.com/laurentiu-miu/springboot-liquibase.git)

**Comment by olavloite** [comment]
> To a spring boot project suppress all logs. Maybe is something related to logbook.xml

I think you're right about that. It is also not really logical for the Spanner Liquibase extension to include a logback configuration.

**Comment by olavloite** [comment]
@laurentiu-miu I think we can close this now that the logback issue has been resolved. Please feel free to reopen or add a new issue if there are other unresolved issues.

**Comment by sebarthel89** [comment]
I try to use it in a spring boot project and could not make it work. Also, execution the demo of @laurentiu-miu feels good but no migration is actually executed, is it ?

https://github.com/laurentiu-miu/springboot-liquibase.git

By upgrading to the latest liquibase-spanner the logging issue is fixed, but nothing is executed for me. Can someone give me a hint how to trigger that actual migration?

**Comment by olavloite** [comment]
> I try to use it in a spring boot project and could not make it work. Also, execution the demo of @laurentiu-miu feels good but no migration is actually executed, is it ?
> 
> https://github.com/laurentiu-miu/springboot-liquibase.git
> 
> By upgrading to the latest liquibase-spanner the logging issue is fixed, but nothing is executed for me. Can someone give me a hint how to trigger that actual migration?

@sebarthel89 I tested the sample application from @laurentiu-miu , and it seems that is is [missing a dependency](https://stackoverflow.com/questions/41960588/liquibase-migration-on-startup-doesnt-work-using-spring-boot) that is required for Liquibase to be executed automatically when Spring Boot is started. I also ran into a couple of other minor problems. Those should be fixed by the changes in this PR: https://github.com/laurentiu-miu/springboot-liquibase/pull/1

@laurentiu-miu Thanks for supplying the sample application in the first place! That is very much appreciated.
