### ISSUE TITLE
Arrays are not correctly generated in changeLogs

### ISSUE THREAD

**Issue by marcindyjas** [cloudspannerecosystem/liquibase-spanner#76]
### Descripton:
Arrays are not correctly generated using both generateChangeLog diffChangeLog command.

### Steps to reproduce:
Use for example DDL as below to create new table on Spanner:

CREATE TABLE TEST_TABLE (
  TEST_ARRAY_STRING ARRAY\<STRING(10)\>,
  TEST_ARRAY_INT64 ARRAY\<INT64\>,
  TEST_ARRAY_TMESTAMP ARRAY\<TIMESTAMP\>,
  TEST_INT64 INT64 NOT NULL,
) PRIMARY KEY(TEST_INT64)

Then run:
liquibase --url="jdbc:cloudspanner:/projects/\<project\>/instances/\<instance\>/databases/\<database\>" --changeLogFile=changeLog.yml generateChangeLog

Examples - changeLog contains:
"ARRAY\<STRING(10)" instead of "ARRAY\<STRING(10)\>"
"ARRAY\<INT64\>(19)" instead of "ARRAY\<INT64\>"
"ARRAY\<TIMESTAMP\>(35)" instead of "ARRAY\<TIMESTAMP\>"

**Comment by olavloite** [comment]
Fixed in #80
