### ISSUE TITLE
FLOAT64 is not correctly generated in changelogs 

### ISSUE THREAD

**Issue by marcindyjas** [cloudspannerecosystem/liquibase-spanner#77]
### Descripton:
Type FLOAT64 is not correctly generated using both generateChangeLog diffChangeLog command.

### Steps to reproduce:
Use for example DDL as below to create new table on Spanner:

CREATE TABLE TEST_TABLE (
  TEST_FLOAT64 FLOAT64 NOT NULL,
) PRIMARY KEY(TEST_FLOAT64)

Then run:
liquibase --url="jdbc:cloudspanner:/projects/\<project\>/instances/\<instance\>/databases/\<database\>" --changeLogFile=changeLog.yml generateChangeLog

ChangeLog contains "FLOAT64(15,16)" instead of "FLOAT64".

**Comment by olavloite** [comment]
Fixed in #80
