### ISSUE TITLE
ChangeLogs with addPrimaryKey to existing table (which is not supported)

### ISSUE THREAD

**Issue by marcindyjas** [cloudspannerecosystem/liquibase-spanner#79]
### Descripton:
When there is more primary keys and they are not added in sequential order liquibase divide its to two operations (createTable, addPrimaryKey) but addPrimaryKey to exisiting table is not supported.

### Steps to reproduce:
Use for example DDL as below to create new table on Spanner:

CREATE TABLE TEST (
  FIRST STRING(3) NOT NULL,
  SECOND DATE NOT NULL,
  THIRD DATE NOT NULL,
  FOURTH INT64 NOT NULL,
  FIFTH STRING(10) NOT NULL,
  CONTENT BYTES(MAX),
) PRIMARY KEY(FIRST, SECOND, FIFTH, FOURTH)

Then run:
liquibase --url="jdbc:cloudspanner:/projects/\<project\>/instances/\<instance\>/databases/\<database\>" --changeLogFile=changeLog.yml generateChangeLog

In generated file there is 2 changesets.
But if we change order in PRIMARY KEY as below - works correctly:

CREATE TABLE TEST (
  FIRST STRING(3) NOT NULL,
  SECOND DATE NOT NULL,
  THIRD DATE NOT NULL,
  FOURTH INT64 NOT NULL,
  FIFTH STRING(10) NOT NULL,
  CONTENT BYTES(MAX),
) PRIMARY KEY(FIRST, SECOND, FOURTH, FIFTH)

**Comment by olavloite** [comment]
This is really strange. I'm not sure whether this is something that we can fix in the Cloud Spanner extension, or whether this is something that sits so deep in Liquibase that we cannot change it. If the latter is the case, we might need to just document this as a limitation.

**Comment by marcindyjas** [comment]
Thanks for the explanation! I think at the moment we can close this issue.
