### ISSUE TITLE
Primary key sort order

### ISSUE THREAD

**Issue by sebarthel89** [cloudspannerecosystem/liquibase-spanner#97]
Hey everybody,

first of all, thank you for providing liquibase spanner support. It works awesome so far, so keep up the good work!

I have questions about defining sort orders for primary keys like this:

```
CREATE TABLE UserAccessLog (
  UserId     INT64 NOT NULL,
  LastAccess TIMESTAMP NOT NULL,
) PRIMARY KEY (UserId, LastAccess DESC);
```

Is it currently supported? If yes, I would be very interested in seeing an example. Maybe, also some documentation should be added about this. I searched the repo and could not find anything in this direction.

Thanks in advance!

**Comment by mescanne** [comment]
Hello -

Liquibase supports order on columns in [create-index](https://docs.liquibase.com/change-types/community/create-index.html), but it doesn't in [create-table](https://docs.liquibase.com/change-types/community/create-table.html).

For the Spanner extension we modify slightly the output from the Liquibase [generateSql](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateTableGenerator.java#L49), and the (PrimaryKeyConstraint)[https://github.com/liquibase/liquibase/blob/a8a00a212a76825a5b8a070e85d6022fbcc2c352/liquibase-core/src/main/java/liquibase/statement/PrimaryKeyConstraint.java#L8] has no ordering.

Given it's not in Liquibase we can't support it in the extension. You can look at using [modify-sql](https://docs.liquibase.com/workflows/liquibase-community/modify-sql.html) to add order for Spanner. A general SQL example is (here)[https://github.com/cloudspannerecosystem/liquibase-spanner/blob/master/example/create-schema.yaml#L59].

Hope this helps.

Mark

**Comment by sebarthel89** [comment]
Alright, will give it a try! thanks :)
